tunnel: aad44139-c1c4-4156-8b46-90deb5010c8c
credentials-file: /etc/cloudflared/creds/aad44139-c1c4-4156-8b46-90deb5010c8c.json
ingress:
  - hostname: api.evbtranding.site
    service: http://backend-nginx-1:80
  - hostname: www.evbtranding.site
    service: http://backend-nginx-1:80
  - service: http_status:404
